CREATE TABLE [RAW_IR_DFY_Request].[IR_DFY_Lead_Imports] (
    ID INT PRIMARY KEY IDENTITY(1,1),
    RecordInsertTimeStamp datetime2(7) NULL,
    UAK uniqueidentifier NULL,
    name NVARCHAR(255),
    phone NVARCHAR(50),
    email NVARCHAR(255),
    email_host NVARCHAR(255),
    website NVARCHAR(255),
    category NVARCHAR(255),
    address NVARCHAR(500),
    city NVARCHAR(255),
    region NVARCHAR(255),
    zip NVARCHAR(10),
    country NVARCHAR(255),
    google_rank INT,
    facebook NVARCHAR(255),
    instagram NVARCHAR(255),
    twitter NVARCHAR(255),
    linkedin NVARCHAR(255),
    googlestars FLOAT,
    googlereviewscount INT,
    yelpstars FLOAT,
    yelpreviewscount INT,
    facebookstars FLOAT,
    facebookreviewscount INT,
    facebookpixel NVARCHAR(255),
    googlepixel NVARCHAR(255),
    criteopixel NVARCHAR(255),
    seo_schema NVARCHAR(MAX),
    googleanalytics NVARCHAR(255),
    linkedinanalytics NVARCHAR(255),
    uses_wordpress BIT,
    mobilefriendly BIT,
    uses_shopify BIT,
    domain_registration DATE,
    domain_expiration DATE,
    domain_registrar NVARCHAR(255),
    domain_nameserver NVARCHAR(255),
    instagram_name NVARCHAR(255),
    instagram_is_verified BIT,
    instagram_is_business_account BIT,
    instagram_media_count INT,
    instagram_highlight_reel_count INT,
    instagram_followers INT,
    instagram_following INT,
    instagram_category NVARCHAR(255),
    instagram_average_likes INT,
    instagram_average_comments INT,
    ads_yelp BIT,
    ads_facebook BIT,
    ads_instagram BIT,
    ads_messenger BIT,
    ads_adwords BIT,
    g_maps BIT,
    g_maps_claimed BIT,
    search_keyword NVARCHAR(255),
    search_city NVARCHAR(255)
    
);

GO
ALTER TABLE [dbo].[IR_DFY_Lead_Imports] ADD  DEFAULT (getdate()) FOR [RecordInsertTimeStamp]
GO
ALTER TABLE [dbo].[IR_DFY_Lead_Imports] ADD  DEFAULT (newsequentialid()) FOR [UAK]
